/**
 * First-run imagery. Three sources, each for what it is good at, all in the background so
 * nothing here blocks a request:
 *
 *  - **Portraits** for every `person` slot are generated by OpenAI (see lib/images), so the
 *    faces belong to nobody. Which face a slot gets falls out of a hash of the file it lands
 *    in; nothing chooses a face for anyone. If generation is unavailable, two free portrait
 *    services are tried, and if those fail too the silhouettes stay and nothing else changes.
 *  - **Stock photography** for any manifest entry with a `pexels` query (wallpapers and the
 *    like), when PEXELS_API_KEY is set.
 *  - **Generated imagery** for any entry with an `openai` prompt — the weather and news
 *    pictures, and anything else a real photo library would not have.
 *
 * Everything is written to the data folder rather than the install folder, which on a
 * packaged app is read-only.
 */
import fs from "node:fs";
import path from "node:path";
import { loadContent } from "./content";
import { assetsWritableRoot, locateAsset } from "./assets";
import type { AssetEntry } from "./assets";
import { generateImage, imageKey, portraitPrompt, seedOf } from "./images";

interface Sourced extends AssetEntry {
  pexels?: { query: string; orientation?: string; size?: string; index?: number };
  openai?: { prompt: string; size?: "1024x1024" | "1536x1024" | "1024x1536"; quality?: string };
}
interface ManifestFile { assets: Record<string, Sourced> }
type G = typeof globalThis & { __foundAssetFetch?: Promise<void> };

export function ensureStockAssets(): Promise<void> {
  const g = globalThis as G;
  if (g.__foundAssetFetch) return g.__foundAssetFetch;
  g.__foundAssetFetch = Promise.all([
    fetchStock().catch((e) => console.warn("[assets] stock fetch failed:", (e as Error).message)),
    fetchGenerated().catch((e) => console.warn("[assets] generated imagery failed:", (e as Error).message)),
    fetchPeople().catch((e) => console.warn("[assets] portraits failed:", (e as Error).message)),
  ]).then(() => undefined);
  return g.__foundAssetFetch;
}

function manifest(): Record<string, Sourced> {
  return loadContent<ManifestFile>("assets.json").assets;
}
/** Where a fetched asset is written: the data folder, which is always writable. */
function destFor(rel: string): string {
  return path.join(assetsWritableRoot(), rel);
}
function save(dest: string, bytes: Buffer): void {
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.writeFileSync(dest, bytes);
}

// ---------- portraits ----------
const GENDER: Record<string, "male" | "female"> = {
  "people.owner": "female", "people.contact.wren": "female", "people.contact.priya": "female",
  "people.contact.mateo": "male", "people.contact.mama": "female", "people.contact.jonah": "male",
  "people.contact.nadia": "female", "people.contact.colin": "male", "people.contact.ilse": "female",
  "people.contact.liam": "male", "people.contact.landlord": "male",
};

async function fetchPeople(): Promise<void> {
  // Slots that name the same file share one face (an account picture and a chat avatar
  // belong to the same human).
  const wanted = new Map<string, { gender: "male" | "female" }>();
  for (const [name, a] of Object.entries(manifest())) {
    if (a.kind !== "person" || !a.file) continue;
    if (a.placeholder === "group") continue; // a group chat wears an icon, not a face
    const dest = destFor(a.file);
    if (locateAsset(a.file) || wanted.has(dest)) continue;
    wanted.set(dest, { gender: GENDER[name] ?? (seedOf(a.file) % 2 ? "male" : "female") });
  }
  if (!wanted.size) return;
  let got = 0, misses = 0;
  for (const [dest, { gender }] of wanted) {
    const bytes = await portrait(gender, dest);
    if (!bytes) {
      // Two people in a row with nothing from any source means there is no route out;
      // stop rather than spend the whole of start-up on it.
      if (++misses >= 2) break;
      continue;
    }
    misses = 0;
    save(dest, bytes);
    got++;
  }
  if (got) console.log(`[assets] ${got} portrait(s) ready`);
}

async function portrait(gender: "male" | "female", dest: string): Promise<Buffer | null> {
  const seed = seedOf(dest);
  for (const source of [generatedPortrait, randomUserPortrait, pravatarPortrait]) {
    try {
      const b = await source(gender, seed);
      if (b && b.length > 2048) return b;
    } catch (e) {
      // Out of allowance, offline, or the service is having a day: try the next one.
      console.warn("[assets] portrait:", (e as Error).message);
    }
  }
  return null;
}

/** A face that belongs to nobody, drawn on request. */
async function generatedPortrait(gender: "male" | "female", seed: number): Promise<Buffer | null> {
  if (!imageKey()) return null;
  return generateImage({ prompt: portraitPrompt(gender, seed), size: "1024x1024" });
}

async function randomUserPortrait(gender: "male" | "female"): Promise<Buffer | null> {
  const res = await fetch(`https://randomuser.me/api/?inc=picture&gender=${gender}&noinfo`, { headers: { accept: "application/json" } });
  if (!res.ok) throw new Error(`randomuser.me HTTP ${res.status}`);
  const data = (await res.json()) as { results?: { picture?: { large?: string } }[] };
  const src = data.results?.[0]?.picture?.large;
  if (!src) return null;
  const img = await fetch(src);
  if (!img.ok) throw new Error(`randomuser.me portrait HTTP ${img.status}`);
  return Buffer.from(await img.arrayBuffer());
}

async function pravatarPortrait(_gender: "male" | "female", seed: number): Promise<Buffer | null> {
  const img = await fetch(`https://i.pravatar.cc/512?u=${seed}`);
  if (!img.ok) throw new Error(`pravatar HTTP ${img.status}`);
  return Buffer.from(await img.arrayBuffer());
}

// ---------- stock photography ----------
async function fetchStock(): Promise<void> {
  const key = process.env.PEXELS_API_KEY;
  if (!key) return;
  const root = assetsWritableRoot();
  const attributionPath = path.join(root, "attribution.json");
  let attribution: Record<string, unknown> = {};
  try { if (fs.existsSync(attributionPath)) attribution = JSON.parse(fs.readFileSync(attributionPath, "utf8")); } catch { attribution = {}; }
  let fetched = 0;
  for (const [name, a] of Object.entries(manifest())) {
    if (!a.pexels || !a.file || locateAsset(a.file)) continue;
    try {
      const { query, orientation = "landscape", size = "large", index = 0 } = a.pexels;
      const res = await fetch(`https://api.pexels.com/v1/search?query=${encodeURIComponent(query)}&orientation=${orientation}&per_page=${index + 1}`, { headers: { Authorization: key } });
      if (!res.ok) { console.warn(`[assets] ${name}: Pexels HTTP ${res.status}`); if (res.status === 429) break; continue; }
      const data = (await res.json()) as { photos?: { src: Record<string, string>; photographer: string; photographer_url: string; url: string }[] };
      const photo = data.photos?.[Math.min(index, (data.photos?.length ?? 1) - 1)];
      if (!photo) continue;
      const img = await fetch(photo.src[size] ?? photo.src.large ?? photo.src.original);
      if (!img.ok) continue;
      save(destFor(a.file), Buffer.from(await img.arrayBuffer()));
      attribution[name] = { photographer: photo.photographer, photographer_url: photo.photographer_url, pexels_url: photo.url, query };
      fetched++;
      fs.mkdirSync(root, { recursive: true });
      fs.writeFileSync(attributionPath, JSON.stringify(attribution, null, 2));
    } catch (e) {
      console.warn(`[assets] ${name}:`, (e as Error).message);
    }
  }
  if (fetched) console.log(`[assets] fetched ${fetched} stock image(s) from Pexels`);
}

// ---------- generated imagery ----------
async function fetchGenerated(): Promise<void> {
  if (!imageKey()) return;
  let made = 0, misses = 0;
  for (const a of Object.values(manifest())) {
    if (!a.openai || !a.file || locateAsset(a.file)) continue;
    const bytes = await generateImage({ prompt: a.openai.prompt, size: a.openai.size, quality: a.openai.quality });
    if (!bytes) { if (++misses >= 2) break; continue; }
    misses = 0;
    save(destFor(a.file), bytes);
    made++;
  }
  if (made) console.log(`[assets] generated ${made} image(s)`);
}
