/** Windows 11 UI glyphs, sourced from Microsoft's Fluent UI System Icons (@fluentui/react-icons). */
import React from "react";
import * as FI from "@fluentui/react-icons";

type P = { size?: number; className?: string; style?: React.CSSProperties };
const wrap = (C: React.ComponentType<{ fontSize?: number; className?: string; style?: React.CSSProperties; primaryFill?: string }>) => ({ size = 16, className, style }: P) => <C fontSize={size} className={className} style={{ display: "block", ...style }} />;

export const ArrowLeft = wrap(FI.ArrowLeft20Regular);
export const ArrowRight = wrap(FI.ArrowRight20Regular);
export const ArrowUp = wrap(FI.ArrowUp20Regular);
export const ArrowDown = wrap(FI.ArrowDown20Regular);
export const Refresh = wrap(FI.ArrowClockwise20Regular);
export const Search = wrap(FI.Search20Regular);
export const ChevronDown = wrap(FI.ChevronDown16Regular);
export const ChevronUp = wrap(FI.ChevronUp16Regular);
export const ChevronRight = wrap(FI.ChevronRight16Regular);
export const ChevronLeft = wrap(FI.ChevronLeft16Regular);
export const Plus = wrap(FI.Add20Regular);
export const Close = wrap(FI.Dismiss20Regular);
export const More = wrap(FI.MoreHorizontal20Regular);
export const MoreVert = wrap(FI.MoreVertical20Regular);
export const Cut = wrap(FI.Cut20Regular);
export const Copy = wrap(FI.Copy20Regular);
export const Paste = wrap(FI.ClipboardPaste20Regular);
export const Rename = wrap(FI.Rename20Regular);
export const Share = wrap(FI.Share20Regular);
export const Delete = wrap(FI.Delete20Regular);
export const Sort = wrap(FI.ArrowSort20Regular);
export const ViewIcon = wrap(FI.Grid20Regular);
export const Filter = wrap(FI.Filter20Regular);
export const DetailsView = wrap(FI.TextBulletListLtr16Regular);
export const LargeIconsView = wrap(FI.Grid16Regular);
export const Pin = wrap(FI.Pin16Regular);
export const Gear = wrap(FI.Settings20Regular);
export const Check = wrap(FI.Checkmark16Regular);
export const Star = wrap(FI.Star20Regular);
export const Power = wrap(FI.Power20Regular);
export const Wifi = wrap(FI.Wifi120Regular);
export const Speaker = wrap(FI.Speaker220Regular);
export const SpeakerMute = wrap(FI.SpeakerMute20Regular);
export const Battery = wrap(FI.Battery1020Regular);
export const TaskView = wrap(FI.SquareMultiple20Regular);
export const Home = wrap(FI.Home20Regular);
export const Monitor = wrap(FI.Desktop20Regular);
export const Globe = wrap(FI.Globe20Regular);
export const Cloud = wrap(FI.Cloud20Regular);
export const Folder = wrap(FI.Folder20Regular);
export const Doc = wrap(FI.Document20Regular);
export const Terminal = wrap(FI.WindowConsole20Regular);
export const Personalize = wrap(FI.PaintBrush20Regular);
export const Display = wrap(FI.Desktop20Regular);
export const NewIcon = wrap(FI.Add20Regular);
export const Undo = wrap(FI.ArrowUndo20Regular);
export const Properties = wrap(FI.DocumentBulletList20Regular);
export const OpenWith = wrap(FI.Open20Regular);
export const Zip = wrap(FI.FolderZip20Regular);
export const Link = wrap(FI.Link20Regular);
export const Eye = wrap(FI.Eye20Regular);
export const Bell = wrap(FI.Alert20Regular);
export const Weather = wrap(FI.WeatherPartlyCloudyDay20Regular);
export const Phone = wrap(FI.Phone20Regular);
export const Keyboard = wrap(FI.Keyboard20Regular);
export const Info = wrap(FI.Info20Regular);
export const Warning = wrap(FI.Warning20Regular);
